### ISSUE TITLE
尾部加号

### ISSUE THREAD

**Issue by hYRamos** [jinht/NewsChannel#1]
设置尾部加号button不显示时,怎么让尾部显示的空白部分去掉..

**Comment by jinht** [comment]
@hYRamos 
![reply_hyramos](https://cloud.githubusercontent.com/assets/13724367/18780900/358e3982-81b2-11e6-990f-15afe8f7187d.jpg)

**Comment by hYRamos** [comment]
```
        额，看错这个宏了，多谢大神！！发自网易邮箱大师
        在2016年09月23日 17:22，Jinht 写道:@hYRamos 
```

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jinht/NewsChannel","title":"jinht/NewsChannel","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jinht/NewsChannel"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jinht in #1: @hYRamos \r\n![reply_hyramos](https://cloud.githubusercontent.com/assets/13724367/18780900/358e3982-81b2-11e6-990f-15afe8f7187d.jpg)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/jinht/NewsChannel/issues/1#issuecomment-249144281"}}}

**Comment by Rachel829** [comment]
想请问一下。尾部加号您是通过什么方法实现前半部分模糊的效果的？

**Comment by jinht** [comment]
@Rachel829 可以设置渐变色啊

**Comment by Rachel829** [comment]
@jinht 渐变色是从 clearcolor 到whitecolor吗 我这么一设置 就出来的结果就是黑色渐变成白色。请问怎么实现透明渐变到白色的效果
