### ISSUE TITLE
频道重复

### ISSUE THREAD

**Issue by zp18862956943** [jinht/NewsChannel#10]
比如总共三个频道，然后一直对频道进行排序、删除。最终就会出现显示上频道多于理应有的量 ，点击后一个导致崩溃@jinht 
![simulator screen shot 2017 1 17 9 23 55](https://cloud.githubusercontent.com/assets/22311048/22022217/f7046ace-dcfb-11e6-8585-2d15f695d4ce.png)

**Comment by jinht** [comment]
@zp18862956943 感谢反馈，现已解决，github项目已做更新
