### ISSUE TITLE
删除频道后VC未能及时清理

### ISSUE THREAD

**Issue by ghost** [jinht/NewsChannel#11]
重新添加Bug,点击加号，点击选中一个可以删除的栏目后，再点击加号，删除选中的栏目(这个时候红色显示的就是)，编辑删除后，又重新添加了一个ScrollView，又回到第一个栏目了

**Comment by jinht** [comment]
@jiaxie9024 
整理一下你说问题
1. 打开编辑频道界面
2. 删除当前选中的频道
3. 收起编辑频道界面后选中的频道变为第一个频道
我整理的没错吧？

**Comment by ghost** [comment]
嗯，是的，这个操作完了，回到第一个频道，此时向右拖拽可以发现上层又多了层scrollview视图

**Comment by jinht** [comment]
@jiaxie9024 好，感谢反馈，我尽快处理一下

**Comment by jinht** [comment]
@jiaxie9024 现已解决，更新即可，再次感谢反馈

**Comment by ghost** [comment]
感谢更新解决问题！这个库挺实用的！有个地方建议改善下：
编辑删除部分
问题描述：目前是点击红色小图标删除，鼠标点击很轻松，但是手指点击起来有点费劲（我把删除图片换成2, 3倍图后，还是如此）
建议改成：处于编辑状态时，点击栏目即可删除

**Comment by jinht** [comment]
@jiaxie9024 我会考虑适当进一步放大点击删除按钮的有效区域
