### ISSUE TITLE
点击穿透Bug

### ISSUE THREAD

**Issue by ghost** [jinht/NewsChannel#12]
弹出编辑时：
1、点击"添加更多栏目“下的栏目 时，栏目上移
2.此时被点击的栏目出现空的底图
3.点击这个底图，会穿透
![1](https://cloud.githubusercontent.com/assets/4465390/23735416/69855338-04c0-11e7-8042-38bcd3cabee9.png)

**Comment by jinht** [comment]
@jiaxie9024 不是很明白你的描述

**Comment by ghost** [comment]
就是点击那个底图会穿透，事件会传递到下面视图，下面视图会被点击到
举个例子：
假设你的这个App一启动，展示的是一个新闻列表主界面A比如（UITableView），正常情况点击cell进入新闻详情
此时，按照上述操作，点击到我说的那个底图，那么主机面A中UITableView 的Cell会被点击到，进入新闻详情了

**Comment by jiaxie9024** [comment]
将那个底图用户交互属性关掉就可以了

**Comment by jinht** [comment]
@jiaxie9024 感谢反馈，问题已经解决，github项目已做更新
