### ISSUE TITLE
大神,求开源啊

### ISSUE THREAD

**Issue by zlp10** [jinht/NewsChannel#13]
大神,求开源啊

**Comment by jinht** [comment]
@Azrial 遇到什么问题了？

**Comment by zlp10** [comment]
跟我们的需求有一点不一样,我没法改

**Comment by jinht** [comment]
@Azrial 你可以看看readMe，我开放了绝大多数的配置接口

**Comment by zlp10** [comment]
这是我看过封装的效果最好的了, 但是还是不太敢用, 我再观望观望

**Comment by jinht** [comment]
@Azrial  你这是什么情况？
![bf5ef446-c286-4eba-8110-7aa0c5706c70](https://cloud.githubusercontent.com/assets/13724367/23987254/a6f76212-0a63-11e7-918c-f69917b5c656.png)

**Comment by zlp10** [comment]
呃呃呃呃, 当时因为不能一窥真理,所有有点心急了,不好意思啊大神, 我不知道这个还会发通知给你的.对此造成的叨扰,再次感到抱歉!我先star了...😊
