### ISSUE TITLE
可否自己增加一个频道数组，还是第一个频道控制展示的VC，第二和第三都可以往里面添加

### ISSUE THREAD

**Issue by yanngxinlei** [jinht/NewsChannel#17]
可否多增加一个频道数组，还是第一个频道控制展示的VC，其余的都可以往里面添加，恳求作者回答一下

**Comment by jinht** [comment]
@yanngxinlei  不是很明白你的意思

**Comment by yanngxinlei** [comment]
就是第一个为已选栏目的栏目块，后面的推荐栏目有好几块，可以自己控制，然后点击下面任何一个模块的 小频道都会添加到已选栏目中，

**Comment by jinht** [comment]
sorry，暂不能满足你的需求

**Comment by yanngxinlei** [comment]
好吧，看来要自己动手啊，害怕自己动手缓存控制不好
