### ISSUE TITLE
why not open it to be open source which we can make it perfect?

### ISSUE THREAD

**Issue by zdrjson** [jinht/NewsChannel#18]

**Comment by zdrjson** [comment]
How can I let the delete icon to the other position, for example, putting on the top right?

**Comment by jinht** [comment]
@zdrjson Sorry, At present, this position is fixed

**Comment by zdrjson** [comment]
Where can I set the position?

**Comment by jinht** [comment]
@zdrjson Sorry, At present, this position is fixed（not adjustable）

**Comment by zdrjson** [comment]
Another question is that do you have plan make it to cocoapods?

**Comment by jinht** [comment]
@zdrjson I'm too busy recently, maybe I can do it later
