### ISSUE TITLE
如果是别个页面跳转过来的,点击加号操作后.再返回并没有dealloc

### ISSUE THREAD

**Issue by gyyxiaogao** [jinht/NewsChannel#21]

**Comment by jinht** [comment]
@gyyxiaogao 能描述的清晰点不？

**Comment by gyyxiaogao** [comment]
就是你这个作为子模块,点击加号操作后,点击返回退出子模块,以下方法并没有执行.
#pragma mark - dealloc
- (void)dealloc {
    NSLog(@"ooo");
}

**Comment by jinht** [comment]
@gyyxiaogao 现已解决
