### ISSUE TITLE
垃圾东西 用tableView有偏移 尼玛还不开源 无语

### ISSUE THREAD

**Issue by stevenkitter** [jinht/NewsChannel#23]
垃圾东西 用tableView有偏移 尼玛还不开源 无语

**Comment by jinht** [comment]
就你这SB，除了到处喷粪还能干啥，你要是不垃圾至于到处求爷爷嘛

**Comment by jinht** [comment]
@stevenkitter 就你这SB，除了到处喷粪还能干啥，你要是不垃圾至于到处求爷爷嘛
