### ISSUE TITLE
sliderView的背景颜色设置

### ISSUE THREAD

**Issue by xayoung** [jinht/NewsChannel#3]
发现只可以修改，频道常规颜色、选中颜色以及轨道颜色，没有找到sliderView的背景颜色设置选项

**Comment by jinht** [comment]
@xayoung 
![Uploading 屏幕快照 2016-11-16 下午5.09.32.png…]()

**Comment by jinht** [comment]
@xayoung 
<img width="712" alt="2016-11-16 5 09 32" src="https://cloud.githubusercontent.com/assets/13724367/20343567/dba6ab5a-ac29-11e6-855f-dabbab897124.png">

**Comment by xayoung** [comment]
@jinht 感谢~

**Comment by Michaelyb520** [comment]
大神，您好，发现修改背景色之后，成这样了
![image](https://cloud.githubusercontent.com/assets/9857312/21000942/96026aea-bd58-11e6-89f1-d8cf5a9a202b.png)

**Comment by Michaelyb520** [comment]
大神，您好，发现修改背景色之后，成这样了
![image](https://cloud.githubusercontent.com/assets/9857312/21000942/96026aea-bd58-11e6-89f1-d8cf5a9a202b.png)
