### ISSUE TITLE
导入sdk后与 Masonry centerY   冲突

### ISSUE THREAD

**Issue by wangsaizzy** [jinht/NewsChannel#37]
项目中所有使用 Masonry 中centerY的全部崩溃

**Comment by jinht** [comment]
@wangsaizzy SDK内部 无centerY此属性，请知晓

**Comment by wangsaizzy** [comment]
方便的话您可以写个Demo试一下，可能是我描述有问题，一旦运行项目，Masonry布局中使用到centerY的全部崩溃，（make.centerY.equalTo(self.centerY).offset(0);）
