### ISSUE TITLE
展开页面的背景色修改

### ISSUE THREAD

**Issue by szmichaelyb** [jinht/NewsChannel#4]
发现修改背景色后不是很理想
![image](https://cloud.githubusercontent.com/assets/9857312/21001023/0083ea9c-bd59-11e6-8ba3-6b869ce00886.png)
另外，展开页面的背景色不知道哪里修改
![image](https://cloud.githubusercontent.com/assets/9857312/21001011/f2c168e4-bd58-11e6-8bfd-6e4221bd70f6.png)

**Comment by jinht** [comment]
@Michaelyb520 这个颜色最好别改成深颜色的

**Comment by jinht** [comment]
@Michaelyb520 这个颜色最好别改成深颜色的，主要考虑的就是浅色系

**Comment by szmichaelyb** [comment]
@jinht 但是我想把你这个SDK用到这个色系的里面。。。。
![wechatimg110](https://cloud.githubusercontent.com/assets/9857312/21002868/fc90ab5a-bd62-11e6-836c-20664721c4f0.png)

**Comment by jinht** [comment]
你可以替换bundle中的相应图片
![1](https://cloud.githubusercontent.com/assets/13724367/21003330/bb563fd0-bd65-11e6-8809-585537715914.png)

**Comment by szmichaelyb** [comment]
这个可以替换，但是点击“+”号展开后的界面背景色就修改不了啊~~~~
能否修改背景色、边框色、和标签文字颜色呢？

**Comment by jinht** [comment]
@Michaelyb520 图片都在bundle里面，相关的属性设置在model里面，希望你仔细了解后再决定是否使用SDK
![2](https://cloud.githubusercontent.com/assets/13724367/21005476/ecc98608-bd6f-11e6-908e-287923ce09d3.png)

**Comment by szmichaelyb** [comment]
我说的是这里的背景色~~~~
你这个背景是半透明的粉色对吗，可否修改啊

![image](https://cloud.githubusercontent.com/assets/9857312/21006135/737dc536-bd72-11e6-97da-8035d10303a8.png)

**Comment by jinht** [comment]
@Michaelyb520 这个背景颜色是带有透明度的白色，目前不可以修改

**Comment by szmichaelyb** [comment]
@jinht 恩恩，大神，啥时候可以提供修改设置扩展（加号）页面的颜色修改接口呢？急等~^_^~

**Comment by jinht** [comment]
@Michaelyb520 背景颜色问题现已做更新，同时增加更多配置选项，详见ReadMe说明，望知晓
