### ISSUE TITLE
求增加更多修正颜色的函数接口

### ISSUE THREAD

**Issue by szmichaelyb** [jinht/NewsChannel#6]
求增加更多修正颜色的函数接口：别忘初衷啊。

![image](https://cloud.githubusercontent.com/assets/9857312/21208442/f54b0318-c2a8-11e6-83dc-dcada7ea11c8.png)

大神，等了好几天啦。。。。。拜托
![image](https://cloud.githubusercontent.com/assets/9857312/21208476/26a5099a-c2a9-11e6-8a83-bad2fc13f364.png)

**Comment by jinht** [comment]
@Michaelyb520 稍安勿躁，近期会做更新。

**Comment by jinht** [comment]
@Michaelyb520 github项目已做相关更新

**Comment by szmichaelyb** [comment]
@jinht 谢谢
