### ISSUE TITLE
缓存功能

### ISSUE THREAD

**Issue by lzc1022** [jinht/NewsChannel#7]
demo里面用的是for数组，在真是的应用中怎么使用啊

**Comment by jinht** [comment]
@lzc12313 设置缓存个数就好，demo就是真实应用的场景
![reply_lzc12313](https://cloud.githubusercontent.com/assets/13724367/21302583/08fe3982-c5f3-11e6-9c4a-5b9683e7b02c.jpg)

**Comment by jinht** [comment]
@lzc12313 设置缓存个数就好，demo就是真实应用的场景
![reply_lzc12313](https://cloud.githubusercontent.com/assets/13724367/21302602/244dd9f4-c5f3-11e6-8032-b7217ecdcd54.jpg)

注：假使符合你的应用场景欢迎点赞使用，不符合的话勿勉强

**Comment by lzc1022** [comment]
- (void)ncCreateData {
    for (NSInteger i = 0; i < 8; i ++) {
        JhtNewsChannelItemModel *model = [[JhtNewsChannelItemModel alloc] init];
        model.titleName = [NSString stringWithFormat:@"NO.%ld", i + 1];
        // 模拟添加频道小红点
        if(i % 3) {
            model.isShowRedPoint = YES;
        } else {
            model.isShowRedPoint = NO;


我定义了model有8个,但是点击删除之后，下次再进来的时候还是8个,没有被删除或是添加上去,缓存个数也设置了

**Comment by jinht** [comment]
@lzc12313 你说的问做本地化存储的问题，这一部分一定是自己弄啊，我要是把这部分都写了的话，发的就不是SKD了，而是一个完整的app啦

**Comment by lzc1022** [comment]
但是如果本地化的话，怎么存储点击的标题啊，我获取不了点击事件啊

**Comment by jinht** [comment]
@lzc12313 你好像忽略了一个回调方法，做本地存储的时机你可以在这个节点做；
![reply_lzc12313_2](https://cloud.githubusercontent.com/assets/13724367/21304949/9f752672-c603-11e6-9d1a-bd1b91ebb7fa.jpg)


关于本地化存储，建议你看看成熟app的做法吧
