### ISSUE TITLE
如果只想某个频道可以排序，不允许删除，怎么实现？

### ISSUE THREAD

**Issue by szmichaelyb** [jinht/NewsChannel#8]
### 这里，`“NO.1”`和`“这是特殊情况”`，`“这是五个字”`，这三个频道。其中`“这是特殊情况”`频道既不允许删除，也不允许移动排序。而`“NO.1”`和`“这是特殊情况”`需要移动排序，但不允许删除（即不显示删除突变，但是可以排序）。如何实现？另外，这个删除按钮的图标，貌似跑到边框线下面去了，有点影响视觉啊。。。

![image](https://cloud.githubusercontent.com/assets/9857312/21303135/379a5164-c5f7-11e6-8ddd-82c30abbc55a.png)

**Comment by jinht** [comment]
不支持这种

**Comment by Michaelyb520** [comment]
希望能早日支持这种需求啊，大神，翘首以盼。。。。

![image](https://cloud.githubusercontent.com/assets/9857312/21303315/8bcce1a6-c5f8-11e6-9b77-b19f334ec228.png)

**Comment by jinht** [comment]
@Michaelyb520 你可以考虑找一个合适SDK啦

**Comment by szmichaelyb** [comment]
@jinht 这个需求要是加入实现了，就完美了，~^_^~很期待啊。。。

**Comment by jinht** [comment]
@Michaelyb520 言重啦，定期我会做更新

**Comment by Michaelyb520** [comment]
@jinht 恩恩，大神大爱无疆啊，辛苦了~~

**Comment by imTango** [comment]
小编，为什么我集成在没有导航栏的VC里，点击加号弹出view不是从顶部覆盖，而是固定的在64的位置，这不应该随着父视图的改变而改变的吗？还有就是没法缓存频道，杀死重新运行应该是记住排序后的频道列表啊，关键没开源，也不好改，废了半天才用了一个特别low的方法给记住排序，希望小编同学能修缮一下，或者添加可以主动更改排序界面的位置的接口

**Comment by jinht** [comment]
@imTango 针对frame问题已做相关开放配置，详见ReadME说明，望知晓
