### ISSUE TITLE
加号按钮失效?

### ISSUE THREAD

**Issue by jiakunyue** [jinht/NewsChannel#9]
您好,我在使用的过程中发现当我第一次进入的时候加号可以点击,退出频道编辑页面滑动到别的页面之后就无法点击加号按钮了!
![snip20161221_1](https://cloud.githubusercontent.com/assets/15082143/21378305/6540f566-c780-11e6-96b0-69c9880f2e2e.png)
想问下加号的点击事件在哪里处理的 !
 万分感谢!!!

**Comment by jinht** [comment]
@jiakunyue 是不是有系统控件在上层？

**Comment by jiakunyue** [comment]
已解决,是我自己的问题!没有仔细阅读代码!
